### ISSUE TITLE
Doesn't build :(

### ISSUE THREAD

**Issue by karimjouini** [philliping/Xamarin-Binding-Intercom-iOS#1]
Hi,

Attending the project to an iOS solutions doesn't build! Namespaces do not appear

**Comment by philliping** [comment]
@karimjouini updated the binding to use the namespace IntercomiOS. There were duplicate instances of the name Intercom before. 
`using IntercomiOS;` should work now.

**Comment by venky284** [comment]
Great work, @philliping 
May we know the version of intercom used here? No mention of it here. Latest being [3.0.17](https://github.com/intercom/intercom-ios)

**Comment by philliping** [comment]
@venky284 its using `3.0.10` 
I'll have to update it to the latest for the enhancements and update the README

**Comment by venky284** [comment]
@philliping Okay, Thanks! Please let us know once it is done.
